-- Displays the first 50 records from the customer table.
-- SELECT * retrieves all columns, while LIMIT 50 restricts
-- the output to only 50 rows.
SELECT * FROM customer LIMIT 50


-- Q1. Total revenue generated by male vs. female customers
-- Groups customers by gender and uses SUM() to calculate
-- the total purchase revenue generated by each gender.
SELECT gender, SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender


---Q2. Which customers used a discount but still spent more than the average purchase amount?
-- The subquery calculates the overall average purchase amount.
-- The main query finds discount users whose spending is equal to or above this average.
SELECT customer_id, purchase_amount 
FROM customer 
WHERE discount_applied = 'Yes' AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer)


-- Q3. Which are the top 5 products with the highest average review rating?
-- Calculates the average rating for each product, rounds it to 2 decimals,
-- sorts from highest to lowest, and returns the top 5 products.
SELECT item_purchased, round(AVG(review_rating::numeric),2) AS "Average Product Rating"
from customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5


--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
-- Filters Standard and Express orders and calculates
-- the average purchase amount for each shipping type.
SELECT shipping_type, 
ROUND(AVG(purchase_amount),2)
FROM customer
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type;


--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
-- Groups customers by subscription status and compares their
-- customer count, average spending, and total revenue.
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount),2) AS avg_spend,
       ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue,avg_spend DESC;


--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
-- Calculates the percentage of purchases made with a discount
-- for each product and returns the top 5 highest rates.
SELECT item_purchased,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
-- Uses CASE to classify customers as New, Returning, or Loyal,
-- then counts the number of customers in each segment.
WITH customer_type AS (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customer)

SELECT customer_segment,COUNT(*) AS "Number of Customers" 
FROM customer_type 
GROUP BY customer_segment;


--Q8. What are the top 3 most purchased products within each category? 
-- Counts purchases for each product and uses ROW_NUMBER()
-- to rank and select the top 3 products within each category.
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;

 
--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
-- Filters customers with more than 5 previous purchases
-- and counts them based on their subscription status.
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;


--Q10. What is the revenue contribution of each age group? 
-- Groups customers by age group, calculates total purchase revenue,
-- and sorts the groups from highest to lowest revenue.
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;


-- Q11. Identify the highest-spending age groups
-- Calculates customer count and average spending for each age group
-- to identify the most valuable age segments.
SELECT age_group,
       COUNT(*) AS total_customers,
       ROUND(AVG(purchase_amount), 2) AS avg_spending
FROM customer
GROUP BY age_group
ORDER BY avg_spending DESC;


-- Q12. Revenue performance by product category
-- Calculates total orders, average purchase value, and total revenue
-- to identify the strongest-performing product categories.
SELECT category,
       COUNT(*) AS total_orders,
       ROUND(AVG(purchase_amount), 2) AS avg_purchase,
       SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY category
ORDER BY total_revenue DESC;


-- Q13. Analyze seasonal sales performance
-- Compares total orders and revenue across seasons
-- to identify seasonal patterns in customer purchasing.
SELECT season,
       COUNT(*) AS total_orders,
       SUM(purchase_amount) AS total_revenue,
       ROUND(AVG(purchase_amount), 2) AS avg_purchase
FROM customer
GROUP BY season
ORDER BY total_revenue DESC;


-- Q14. Analyze customer spending by payment method
-- Compares usage and average spending across payment methods
-- to identify methods associated with higher-value purchases.
SELECT payment_method,
       COUNT(*) AS total_transactions,
       ROUND(AVG(purchase_amount), 2) AS avg_purchase,
       SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY payment_method
ORDER BY avg_purchase;


-- Q15. Rank products by revenue performance
-- Calculates revenue for each product and uses DENSE_RANK()
-- to rank products from highest to lowest revenue.
SELECT item_purchased,
       SUM(purchase_amount) AS total_revenue,
       DENSE_RANK() OVER (
           ORDER BY SUM(purchase_amount) DESC
       ) AS revenue_rank
FROM customer
GROUP BY item_purchased
ORDER BY revenue_rank;
